version: '3'
services:
  api:
    restart: always
    build: ./API
    ports:
      - '5051:5051'
    volumes:
      - ./API:/app
  auto:
    restart: always
    build: ./AUTO
    volumes:
      - ./AUTO:/app
  autohist:
    restart: always
    build: ./AUTOHIST
    volumes:
      - ./AUTOHIST:/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - datos_mongodb:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
volumes:
  datos_mongodb: